### ISSUE TITLE
总是在足够远处激增

### ISSUE THREAD

**Issue by RingoTC** [JacksonWuxs/19nCoV-SEIR-Estimation#1]
在最后预测时，总是会出现这样的情况：
如果预测的步数选择较近，能看到预测的曲线与实际情况贴合较好
![image 0](https://user-images.githubusercontent.com/6525061/74608952-6431a580-5120-11ea-85d8-a2688f9c5619.png)
但是当预测的步数选择足够远时会发现，曲线总是在足够远处激增
![image 1](https://user-images.githubusercontent.com/6525061/74608976-86c3be80-5120-11ea-87b0-813a6e3c8875.png)
比如预测100天时，则曲线在90天左右激增；预测1000天时，则在990天左右激增。
这是为何？

**Comment by JacksonWuxs** [comment]
非常高兴收到你提出的issue，对于你提出的问题我提出的解释是：由于我的模型中每期新增感染者 = alpha1 * 潜伏者 + alpha2 * 确诊患者，所以每一期新增的患者数都都与未感染人数无关。然而实际上，随着病毒感染的人越来越多，这导致易感人群逐渐减少，实际上R0是会在远期下降的。

举个例子，在感染初期，由于病毒不受人们重视，所以R0假设为3.5；随着越来越多的人感染到了这个病毒，所以病毒可以感染的未感染者会变少，那么感染者接触未感染者的概率会下降，于是R0可能会下降到一个比3.5小的数字。

也就是说，每期新增感染人数应该是一个与易感人群规模、潜伏者和确诊患者的函数。而在我的模型中，**由于在感染初期，武汉市的人口规模并不会成为病毒感染的显著限制之一，所以我定义的新增感染人数与易感人群规模无关**。最后的结果就是，随着潜伏者和确诊患者的激增，感染者也会激增，所以**该模型并不适用于预测病毒感染中后期的估计**。

对此，您可以做出如下修改：
1. 把模型的新增患者数修改为一个动态的函数，许多研究已经包含此相关的内容您可以进行借鉴。
2. 在疫情发展的初期、中期、后期和末期分别拟合模型估计分阶段R0。
