### ISSUE TITLE
能说下参数的设定思路吗

### ISSUE THREAD

**Issue by bashanyeyu** [JacksonWuxs/19nCoV-SEIR-Estimation#2]
方程中的alpha beta等

**Comment by JacksonWuxs** [comment]
下载文档看一下我设计的模型就好了伐~ 
比如 $\alpha1$ 是潜伏者能感染病人的概率，所以公式$\frac{\partial E}{\partial t} = \alpha1 E + \alpha2 I - \beta E$中的第一部分就是有多少新增潜伏者是由其他潜伏者感染的嘛。

**Comment by bashanyeyu** [comment]
是哇 现在公开的数据中没有能够说明这个概率的内容a啊 在实际估算地区的发展情况时候 随便设置会不会导致结果的不正确啊

**Comment by JacksonWuxs** [comment]
这个alpha1具体是多少，是模型基于已有数据拟合出来的哈。至于这些关系的定义，是基于流行病学的研究成果的。我这是基于SEIR模型进行的一点点小的修改而已，而SEIR、SIR、SI等模型都是由流行病专家研究出来的。

**Comment by bashanyeyu** [comment]
> 这个alpha1具体是多少，是模型基于已有数据拟合出来的哈。至于这些关系的定义，是基于流行病学的研究成果的。我这是基于SEIR模型进行的一点点小的修改而已，而SEIR、SIR、SI等模型都是由流行病专家研究出来的。

好的好的 我去搜下大佬们的论文学习学习 多谢！

**Comment by bashanyeyu** [comment]
> 这个alpha1具体是多少，是模型基于已有数据拟合出来的哈。至于这些关系的定义，是基于流行病学的研究成果的。我这是基于SEIR模型进行的一点点小的修改而已，而SEIR、SIR、SI等模型都是由流行病专家研究出来的。

好的好的 我去搜下大佬们的论文学习学习 多谢！

**Comment by bashanyeyu** [comment]
好的好的 我去搜下大佬们的论文学习学习 多谢！
