### ISSUE TITLE
预测的确诊数都是直线上升？

### ISSUE THREAD

**Issue by liuhongwei2018** [JacksonWuxs/19nCoV-SEIR-Estimation#3]
您好，今天用您的代码分析跑了河南、广东和浙江的数据，这三地的到目前为止确诊数据均出现顶峰，但模型预测都是直线上升，三个地方的数据均是这样，请问是什么原因？
![image](https://user-images.githubusercontent.com/40065347/75112915-ca1faf00-5683-11ea-9165-f77e856937bf.png)

**Comment by JacksonWuxs** [comment]
出现直线上升的原因有两个方面：
1. 我的模型的假设是：新增感染人数 = alpha1 * 潜伏者 + alpha2 * 确诊患者。可以看出，在我的模型中感染人数只与当前感染总人数有关。所以，只要没有在比较长的一段时间内处于无人感染的状态，模型会一直预测有新增患者的。

2. 出现这个上述问题的原因在于，我们在模型中的假设是感染率为常数（alpha1和alpha2为常数）。然而，真实情况是，感染率是会随着病情的发展和人们的控制逐渐下降的。也就是说，alpha应该是动态的。以广东省为例，现在的模型学习到感染率的都是前段刚爆发期间的情况。也就是说，如果没有那么多管制政策，那么感染人数就是你现在预测出的那条线了。然而，一系列的管制政策使得感染率开始变小，二我们的模型还没发拟合到这一点，所以就会出现预测的确诊数一直上升的情况了。

为了精准预测，我有两个改进建议：
1. 单独拿这几天开始下降以后的数据进行拟合。考虑到我们总共有5个参数要拟合，所以你至少要拿5天的数据。
2. 此外，你还可以把alpha1和alpha2改写为一个函数，函数为：新增感染人数 = 接触人数 * 感染率。这个接触人数可能包括当日地铁使用量之类的指标来反映当前社会的活跃情况。此时，预测的alpha'就不是直接的感染率了，而是患者接触1个人能有多大几率感染他。在这种情况下，随着限制措施的实施，“接触人数”实际上是下降的，也就是说新增感染人数会随之下降的。
