### ISSUE TITLE
参数的设定

### ISSUE THREAD

**Issue by yyangjie** [JacksonWuxs/19nCoV-SEIR-Estimation#4]
你好，我想请问一下模型中的 loss, r2 = seir.score(9000000, potential, 45, 15, 2, Y=train) ，45，12，2是怎么得来的呢

**Comment by yyangjie** [comment]
你好 ，我还想再请问一下，1100是怎么设定的呀，也可以是其他比它更大的数吗?
       r1 = r2_score(Y['治愈'], est['治愈'])
        r2 = r2_score(Y['死亡'], est['死亡'])
        r3 = r2_score(Y['确诊'], est['确诊'])为什么都用r2_score呀
模型最后输出结果的模型R2,指的是模型预测的准确率吗？
真的不好意思，我是个小白，，，看了好久都没弄明白，期待您的解答，万分感谢！

**Comment by yyangjie** [comment]
你好，我先想问一下50，1100是怎么选择的呀，可以是其他更大的数吗

**Comment by JacksonWuxs** [comment]
45,12,2是从原始数据中得到的。
50，1100是我网格搜索的范围，你可以自己设置范围

**Comment by yyangjie** [comment]
45，12，2是确诊人数死亡人数出院人数，还是新增的呀，具体是哪天的数据呀。我找了几个都对不上。最后结果怎么知道预测的就是23号的呢，不是其他日期的呢？

**Comment by JacksonWuxs** [comment]
根据模型的定义，45，12，2是指初始状态时候的确诊、死亡、治愈人数。在本项目中，这三个数值取截止1月16日的武汉市累计确诊、死亡、治愈数量。

**Comment by yyangjie** [comment]
那估计出来的潜在感染人数为什么就是23号的呀，根据模型里面的定义估计出来的不应该是截止16号的潜在感染人数吗

**Comment by JacksonWuxs** [comment]
谢谢你的提醒，此处为笔误写成了23号

**Comment by yyangjie** [comment]
那个train里面的数据，17号的新增的，其余日期的是累计的，是不是应该把17号的也变成累计的呢？

**Comment by yyangjie** [comment]
我还想请问一下模型的总体思路，是通过数据利用退火优化求出五个参数，然后估计一下16号的E是吗？关于数据的选择，需要考虑到政策因素吗？比如利用23号封城之前的数据？

**Comment by JacksonWuxs** [comment]
估计E不是目的，目的是求出封城以前的病毒再生系数R0。

**Comment by yyangjie** [comment]
意思是估计出来的R0是16日到2月11日的，认为这段时间内的再生数相等是吗

**Comment by JacksonWuxs** [comment]
对的。因为24号才封城嘛，算潜伏期15日左右。所以取到2月11日的数据，认为这段时间出现的病例都是封城前感染的。所以最后出来的R0=2.39相当于这个病在现代化城市中的再生系数。这个数值和世卫组织估计的区间2-2.5差不多。

**Comment by yyangjie** [comment]
我估计的是6点多，和之前国内团队利用1月21日之前估计出来的差不多

**Comment by JacksonWuxs** [comment]
我觉得完全依靠1月21日之前的数据计算出的R0可信度较低。理由有二：其一，数据量较少，模型拟合效果较差；其二，1月16日以前的数据由于筛查方法不先进和医院重视度不太有效，可能会因此做出错误的结论

**Comment by yyangjie** [comment]
我也是用17日到2月11日的数据做的，和你设置的参数一样，就是train里面17日的数据用的是累计数据。你用的是新增的。
