### ISSUE TITLE
微分方程形式

### ISSUE THREAD

**Issue by dashuaiya97** [JacksonWuxs/19nCoV-SEIR-Estimation#5]
您好，请问为什么您模型的ds/dt的方程跟网上搜到的模型的微分方程不太一样啊，他们是用易感×确诊，可以解答一下吗

**Comment by JacksonWuxs** [comment]
我觉得还是可以理解的吧。在病毒初期，易感人数约等于总人口。

**Comment by dashuaiya97** [comment]
那大概到几月的数据用这个模型算是比较准确的啊，居家隔离那段时间易感人数少了很多是不是就不能用了？
