### ISSUE TITLE
换城市后潜伏期变成了70天

### ISSUE THREAD

**Issue by yijunwang0805** [JacksonWuxs/19nCoV-SEIR-Estimation#6]
你好，

感谢您在百忙之中抽空看我提的issue！谢谢您的代码的分享！

我运用您的代码跑了香港的数据，数据范围为从一月份至今。

但是结果让人匪夷所思。平均潜伏期过于冗长，近70日。

 - 平均潜伏期为：69.53天
 - 病毒再生基数：1.91
 - 确诊R2：0.7073
 - 死亡R2：0.6679
 - 治愈R2：-0.4574
 - 模型R2：0.3060
 - 模型总误差：487.6618

请问这是为什么呢？
以下是图片明细。

![afe1eb47994b018ee126334cb20e8b9](https://user-images.githubusercontent.com/56286591/88005526-2d7f1180-cb3c-11ea-9c9d-a8ef720040be.png)
![294d8e73205bbae6b9aa02813dc7fea](https://user-images.githubusercontent.com/56286591/88005528-2f48d500-cb3c-11ea-9352-529b54b6c55e.png)
![ce46ace48e9a363bcbc125b5f671694](https://user-images.githubusercontent.com/56286591/88005534-31ab2f00-cb3c-11ea-9b47-321ee935851e.png)

**Comment by JacksonWuxs** [comment]
本研究目的是分析病毒在无人控制情况下城市环境中的自然传播率。

因此，研究使用的模型利用了几个很强的假设：1. 研究期间内病毒的传播能力R0没有发生改变；2. 城市内部的易感人群数量没有显著变化。

在你研究香港的案例中，香港政府逐渐施行越来越严格的管控措施，并且医院也积累了更多的医治经验。即政府的政策降低了病毒传播能力，医院水平降低了死亡率，导致整个病毒的感染系数R0发生了改变。因此，该数据违背了模型的假设，模型的输出结果不可信。这解释了为何3张图片在坐标轴<=50的时候看起来拟合的还不错，但之后拟合的较差的原因 —— 50天后香港的管控措施使得病毒感染系数R0发生了改变。
