### ISSUE TITLE
关于模型的参数问题

### ISSUE THREAD

**Issue by wslhd** [JacksonWuxs/19nCoV-SEIR-Estimation#8]
![image](https://user-images.githubusercontent.com/57095720/91635869-8476e100-ea2e-11ea-8685-9d6b545a0590.png)
老哥，看了你2月对武汉的新冠病毒分析，想请教你图片中的数值参数是根据什么取的

**Comment by JacksonWuxs** [comment]
9000000是武汉市的常住人口数900万人；
potential是指2020年1月16日武汉市有多少个潜伏期病人；
45是指2020年1月15日官方公布的确诊人数；
15是指2020年1月15日官方公布的治愈人数；
2是指2020年1月15日官方公布的死亡人数。
